### ISSUE TITLE
内容展示是否可以用wxParser来实现

### ISSUE THREAD

**Issue by kinghunki** [KuangPF/wxAPP_toutiaoNews#1]
内容展示是否可以用wxParser来实现呢？
用wxParser来解析html内容！

**Comment by KuangPF** [comment]
由于接口返回的直接是一个 `html` 链接，并不是 `html` 内容，因此` wxParse` 也无法实现吧。

![tim 20180425232343](https://user-images.githubusercontent.com/20694238/39255914-33ce3420-48e0-11e8-8b51-0a0263ece7f5.png)
