### ISSUE TITLE
100次有点少

### ISSUE THREAD

**Issue by jalenFish** [KuangPF/wxAPP_toutiaoNews#4]
如果是官方限制的话，可不可以注册多个api实现多次调用呢？
或者是一天内定时任务去读取内容，把内容保存到本地数据库供大家读取呢

**Comment by KuangPF** [comment]
目前超时后会读取本地 [mock](https://github.com/KuangPF/wxAPP_toutiaoNews/blob/master/mocks/index.js)，除了新闻内容不是最新的外，其他是一样的。
